#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'nmax'

count_argument = ARGV.first.to_i

puts(STDIN.map { |line| Nmax.call(count_argument, line) }
          .flatten
          .sort
          .last(count_argument))
